<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0"/>
		<PackageReference Include="xunit.v3" Version="4.0.0"/>
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2"/>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\ExtendedThreading\ExtendedThreading.csproj"/>
	</ItemGroup>

</Project>
